#! /usr/bin/env node
import fs from "node:fs/promises";
const filePath = process.argv[2];

const content = await fs.readFile(filePath, "utf-8");
const wordArray = content.split(/[ ,.'’\-\/\r\n]+/);

const output = {};
wordArray.forEach((word, indx, arr) => {
  word in output ? (output[word] = output[word] + 1) : (output[word] = 1);
});

console.table(output);
