#! /usr/bin/env node
import fs from "node:fs/promises";
const [nodeLocation, currentDir, filePath, word] = process.argv;

const content = await fs.readFile(filePath, "utf-8");
const wordArray = content.split(/[ ,.'’\-\/\r\n]+/);

const output = {};
wordArray.forEach((word, indx, arr) => {
  word in output ? (output[word] += 1) : (output[word] = 1);
});

!word
  ? console.table(output)
  : word in output
  ? console.table(`${word}: ${output[word]}`)
  : console.error("Sorry , Word not found");
